#!/usr/bin/env sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/.." && pwd)
output_dir="$repo_root/dist"
output_path="$output_dir/cityu-campus-assistant.md"
temporary_path="$output_path.tmp"

mkdir -p "$output_dir"
trap 'rm -f "$temporary_path"' EXIT HUP INT TERM

{
  printf '%s\n' '# CityU Macau Campus Assistant - Combined Knowledge Package'
  printf '\n'
  printf '%s\n' '> Generated from the repository source files. Do not edit this file directly.'
  printf '%s\n' '> Time-sensitive admissions, fees, accommodation, and immigration information must be checked against current official notices.'

  for source_path in \
    'skills/cityu-macau-campus-assistant/SKILL.md' \
    'skills/cityu-macau-campus-assistant/references/freshman.md' \
    'skills/cityu-macau-campus-assistant/references/fds.md'
  do
    if [ ! -f "$repo_root/$source_path" ]; then
      printf '%s\n' "Missing source file: $source_path" >&2
      exit 1
    fi

    printf '\n---\n\n'
    printf '<!-- SOURCE: %s -->\n\n' "$source_path"
    awk '
      {
        sub(/\r$/, "")
        sub(/[ \t]+$/, "")
        lines[NR] = $0
        if ($0 !~ /^[[:space:]]*$/) {
          last = NR
        }
      }
      END {
        for (line = 1; line <= last; line++) {
          print lines[line]
        }
      }
    ' "$repo_root/$source_path"
  done
} > "$temporary_path"

mv "$temporary_path" "$output_path"
printf '%s\n' "Created $output_path"
