$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$outputDirectory = Join-Path $repoRoot "dist"
$outputPath = Join-Path $outputDirectory "cityu-campus-assistant.md"
$sources = @(
    "SKILL.md",
    "knowledge-base/freshman.md",
    "knowledge-base/fds.md"
)

$sections = [System.Collections.Generic.List[string]]::new()
$sections.Add("# CityU Macau Campus Assistant - Combined Knowledge Package")
$sections.Add("")
$sections.Add("> Generated from the repository source files. Do not edit this file directly.")
$sections.Add("> Time-sensitive admissions, fees, accommodation, and immigration information must be checked against current official notices.")

foreach ($sourcePath in $sources) {
    $fullPath = Join-Path $repoRoot $sourcePath
    if (-not (Test-Path -LiteralPath $fullPath -PathType Leaf)) {
        throw "Missing source file: $sourcePath"
    }

    $content = Get-Content -Raw -Encoding utf8 $fullPath
    $content = $content -replace "`r`n", "`n"
    $content = $content -replace "[ `t]+(?=`n|$)", ""
    $content = $content.Trim()

    $sections.Add("")
    $sections.Add("---")
    $sections.Add("")
    $sections.Add("<!-- SOURCE: $sourcePath -->")
    $sections.Add("")
    $sections.Add($content)
}

$output = ($sections -join "`n") + "`n"
$utf8WithoutBom = [System.Text.UTF8Encoding]::new($false)

New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
[System.IO.File]::WriteAllText($outputPath, $output, $utf8WithoutBom)

Write-Host "Created $outputPath"
